name: UHCPlugin
version: 1.8.0
authors:
  - Balduvian
  - Sumdumdude
  - C1fr1
  - Rewind
  - roobley
  - mclonergan
load: STARTUP
main: com.codeland.uhc.UHCPlugin
api-version: 1.17
depend:
  - ProtocolLib