name: UHCPlugin
version: 1.7.3
authors:
  - Balduvian
  - Sumdumdude
  - C1fr1
  - Rewind
  - roobley
  - mclonergan
load: STARTUP
main: com.codeland.uhc.UHCPlugin
api-version: 1.16
depend:
  - ProtocolLib