package com.codeland.uhc.quirk

import org.bukkit.Material
import org.bukkit.Material.*

object Creative {
	val blocks = arrayOf<Material>(
		COBBLESTONE,
		COBBLESTONE_SLAB,
		COBBLESTONE_STAIRS,
		COBBLESTONE_WALL,

		STONE,
		STONE_SLAB,
		STONE_STAIRS,

		STONE_BRICKS,
		STONE_BRICK_SLAB,
		STONE_BRICK_STAIRS,
		STONE_BRICK_WALL,

		DIRT,
		GRASS_BLOCK,
		STONE_SLAB,

		NETHERRACK,
		MAGMA_BLOCK,
		NETHER_BRICKS,
		NETHER_BRICK_FENCE,
		NETHER_BRICK_STAIRS,
		NETHER_BRICK_SLAB,
		NETHER_BRICK_WALL,

		TORCH,
		CAMPFIRE,
		SOUL_TORCH,
		SOUL_CAMPFIRE,

		GRANITE,
		GRANITE_SLAB,
		GRANITE_STAIRS,
		GRANITE_WALL,
		POLISHED_GRANITE,
		POLISHED_GRANITE_SLAB,
		POLISHED_GRANITE_STAIRS,

		ANDESITE,
		ANDESITE_SLAB,
		ANDESITE_STAIRS,
		ANDESITE_WALL,
		POLISHED_ANDESITE,
		POLISHED_ANDESITE_SLAB,
		POLISHED_ANDESITE_STAIRS,

		DIORITE,
		DIORITE_SLAB,
		DIORITE_STAIRS,
		DIORITE_WALL,
		POLISHED_DIORITE,
		POLISHED_DIORITE_SLAB,
		POLISHED_DIORITE_STAIRS,

		OAK_FENCE,
		SPRUCE_FENCE,
		DARK_OAK_FENCE,
		BIRCH_FENCE,
		ACACIA_FENCE,
		JUNGLE_FENCE,
		WARPED_FENCE,
		CRIMSON_FENCE,
		OAK_SLAB,
		SPRUCE_SLAB,
		DARK_OAK_SLAB,
		BIRCH_SLAB,
		ACACIA_SLAB,
		JUNGLE_SLAB,
		WARPED_SLAB,
		CRIMSON_SLAB,
		OAK_STAIRS,
		SPRUCE_STAIRS,
		DARK_OAK_STAIRS,
		BIRCH_STAIRS,
		ACACIA_STAIRS,
		JUNGLE_STAIRS,
		WARPED_STAIRS,
		CRIMSON_STAIRS,
		OAK_PRESSURE_PLATE,
		SPRUCE_PRESSURE_PLATE,
		DARK_OAK_PRESSURE_PLATE,
		BIRCH_PRESSURE_PLATE,
		ACACIA_PRESSURE_PLATE,
		JUNGLE_PRESSURE_PLATE,
		WARPED_PRESSURE_PLATE,
		CRIMSON_PRESSURE_PLATE,

		REDSTONE,
		PISTON,
		STICKY_PISTON,
		REPEATER,
		COMPARATOR,
		REDSTONE_BLOCK,
		REDSTONE_TORCH,
		DISPENSER,
		DROPPER,
		TARGET,
		STONE_PRESSURE_PLATE,
		HEAVY_WEIGHTED_PRESSURE_PLATE,
		LIGHT_WEIGHTED_PRESSURE_PLATE
	)

	init {
		blocks.sort()
	}
}